
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Core.java
 *
 * Created on 13-nov-2011, 12:41:33
 */
/**
 *
 * @author Microsoft User
 */
public class Core extends javax.swing.JFrame {

    /** Creates new form Core */
    public Core() {
        initComponents();
        swSda = new StopWatch();
        swBrecht = new StopWatch();
        swBros = new StopWatch();
        swBrihos = new StopWatch();
        swEzel = new StopWatch();
        swKouter = new StopWatch();
        swLila = new StopWatch();
        swWestlandia = new StopWatch();
        swZk = new StopWatch();        
        secT = new Timer(1000, new secHandler());
        minT = new Timer(60000, new minHandler());
        hoursT = new Timer (3600000, new hourHandler());        
    }
        
    
    class secHandler implements ActionListener{
        public void actionPerformed(ActionEvent e){
        sec++;        
        lSec.setText(""+String.format("%02d",sec));
        if (sec==59){sec=-1;}
        }
    }
        
    class minHandler implements ActionListener{
        public void actionPerformed(ActionEvent e){
        min++;
        lMin.setText(""+String.format("%02d",min));
        if (min==59){min=-1;}
    }
    }
    
    class hourHandler implements ActionListener{
        public void actionPerformed(ActionEvent e){
        hours++;
        lUren.setText(""+String.format("%02d",hours));
        if (hours==23){hours=-1;}
        }
    }
    
  


     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        start = new javax.swing.JButton();
        lUren = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lMin = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lSec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lilaTime = new javax.swing.JLabel();
        lilaStop = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        brosStop = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        brosTime = new javax.swing.JLabel();
        westlandiaStop = new javax.swing.JButton();
        westlandiaTime = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        zkStop = new javax.swing.JButton();
        zkTime = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sdaStop = new javax.swing.JButton();
        sdaTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brechtStop = new javax.swing.JButton();
        brechtTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        brihosStop = new javax.swing.JButton();
        brihosTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ezelStop = new javax.swing.JButton();
        kouterTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kouterStop = new javax.swing.JButton();
        ezelTime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rapste Vat Oostende");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1267, 200));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        lUren.setFont(new java.awt.Font("Lucida Console", 0, 72)); // NOI18N
        lUren.setForeground(new java.awt.Color(255, 255, 255));
        lUren.setText("00");

        jLabel2.setFont(new java.awt.Font("Blood Of Dracula", 0, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(":");

        lMin.setFont(new java.awt.Font("Lucida Console", 0, 72)); // NOI18N
        lMin.setForeground(new java.awt.Color(255, 255, 255));
        lMin.setText("00");

        jLabel11.setFont(new java.awt.Font("Blood Of Dracula", 0, 72)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");

        lSec.setFont(new java.awt.Font("Lucida Console", 0, 72)); // NOI18N
        lSec.setForeground(new java.awt.Color(255, 255, 255));
        lSec.setText("00");

        jLabel1.setFont(new java.awt.Font("Blood Of Dracula", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("De Zwarte Kielen");

        jLabel8.setFont(new java.awt.Font("Blood Of Dracula", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rapste Vat Oostende");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(73, 73, 73)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(lUren)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lMin)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lSec)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(reset)
                        .addGap(175, 175, 175)
                        .addComponent(start)
                        .addGap(344, 344, 344))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lUren)
                            .addComponent(jLabel2)
                            .addComponent(lMin)
                            .addComponent(jLabel11)
                            .addComponent(lSec))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(reset))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1709, 350));

        lilaTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lilaTime.setForeground(new java.awt.Color(240, 240, 240));
        lilaTime.setText("Niet gekomen");

        lilaStop.setText("Stop");
        lilaStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lilaStopActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/lila.jpg"))); // NOI18N

        brosStop.setText("Stop");
        brosStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brosStopActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/bros.jpg"))); // NOI18N

        brosTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brosTime.setForeground(new java.awt.Color(240, 240, 240));
        brosTime.setText("00:10:17:478");

        westlandiaStop.setText("Stop");
        westlandiaStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westlandiaStopActionPerformed(evt);
            }
        });

        westlandiaTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        westlandiaTime.setForeground(new java.awt.Color(240, 240, 240));
        westlandiaTime.setText("DNF");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/westlandia.jpg"))); // NOI18N

        zkStop.setText("Stop");
        zkStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zkStopActionPerformed(evt);
            }
        });

        zkTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        zkTime.setForeground(new java.awt.Color(240, 240, 240));
        zkTime.setText("00:15:08:163");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/zk.jpg"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("© Wago - Zwarte Kielen 2012");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lilaStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(118, 118, 118)
                        .addComponent(brosStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(westlandiaStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lilaTime))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(brosTime))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(westlandiaTime)
                            .addComponent(jLabel13))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(zkStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(zkTime)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lilaStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brosStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(westlandiaStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zkStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lilaTime)
                    .addComponent(zkTime)
                    .addComponent(westlandiaTime)
                    .addComponent(brosTime))
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(91, 91, 91))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1129, 200));

        sdaStop.setText("Stop");
        sdaStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdaStopActionPerformed(evt);
            }
        });

        sdaTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sdaTime.setText("00:28:17:632");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/sda.jpg"))); // NOI18N
        jLabel3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sda.jpg"))); // NOI18N

        brechtStop.setText("Stop");
        brechtStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brechtStopActionPerformed(evt);
            }
        });

        brechtTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brechtTime.setText("DNF");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/brecht.jpg"))); // NOI18N

        brihosStop.setText("Stop");
        brihosStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brihosStopActionPerformed(evt);
            }
        });

        brihosTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brihosTime.setText("DNF");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/brihos.jpg"))); // NOI18N

        ezelStop.setText("Stop");
        ezelStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ezelStopActionPerformed(evt);
            }
        });

        kouterTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kouterTime.setForeground(new java.awt.Color(255, 255, 255));
        kouterTime.setText("00:00:00:00");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/ezel.jpg"))); // NOI18N

        kouterStop.setText("Stop");
        kouterStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kouterStopActionPerformed(evt);
            }
        });

        ezelTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ezelTime.setText("DNF");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuurkes/kouter.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(sdaStop, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addComponent(sdaTime))
                .addGap(85, 85, 85)
                .addComponent(brechtStop, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(148, 148, 148)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(brihosStop, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(brihosTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(ezelStop, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(125, 125, 125)
                        .addComponent(kouterStop, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ezelTime)
                        .addGap(63, 63, 63)
                        .addComponent(kouterTime)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brechtTime))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(105, 105, 105)
                .addComponent(jLabel5)
                .addGap(120, 120, 120)
                .addComponent(jLabel6)
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sdaStop)
                        .addComponent(brechtStop)
                        .addComponent(brihosStop))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(kouterStop)
                        .addComponent(ezelStop)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brechtTime)
                    .addComponent(sdaTime)
                    .addComponent(brihosTime)
                    .addComponent(ezelTime)
                    .addComponent(kouterTime))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        //resetten van alle stopwatches en de hoofdtijd die apart loopt
        swSda.reset();
        swBrecht.reset();
        swBros.reset();
        swEzel.reset();
        swKouter.reset();
        swLila.reset();
        swWestlandia.reset();
        swZk.reset();
        swBrihos.reset();       
        
        //stoppen van de timers en de labels op nul zetten
        //msecT.stop();
        secT.stop();
        minT.stop();
        hoursT.stop();
        //de int waarden op nul plaatsen
        hours=0;
        min=0;
        sec=0;
        msec=0;
        lUren.setText("00");
        lMin.setText("00");
        lSec.setText("00");       
    }//GEN-LAST:event_resetActionPerformed

    private void sdaStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdaStopActionPerformed
        //stop tijd van sda
        swSda.stop();
        String time =swSda.getElapsedTime();
        sdaTime.setText(time);
        //System.out.println(time);
       
        
        
    }//GEN-LAST:event_sdaStopActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        //Start alle stopwatches
        swSda.start();
        swBrecht.start();
        swBros.start();
        swEzel.start();
        swKouter.start();
        swLila.start();
        swWestlandia.start();
        swZk.start();    
        swBrihos.start();
        //start de hoofdtimer
        //msecT.start();
        secT.start();
        minT.start();
        hoursT.start();
        
        
            
        
        
    }//GEN-LAST:event_startActionPerformed

    private void lilaStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lilaStopActionPerformed
        swLila.stop();
        String time =swLila.getElapsedTime();
        lilaTime.setText(time);
        //System.out.println(time);
    }//GEN-LAST:event_lilaStopActionPerformed

    private void brechtStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brechtStopActionPerformed
        swBrecht.stop();
        String time =swBrecht.getElapsedTime();
        brechtTime.setText(time);        
    }//GEN-LAST:event_brechtStopActionPerformed

    private void brihosStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brihosStopActionPerformed
        swBrihos.stop();
        String time =swBrihos.getElapsedTime();
        brihosTime.setText(time);
    }//GEN-LAST:event_brihosStopActionPerformed

    private void ezelStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ezelStopActionPerformed
        swEzel.stop();
        String time =swEzel.getElapsedTime();
        ezelTime.setText(time);
    }//GEN-LAST:event_ezelStopActionPerformed

    private void kouterStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kouterStopActionPerformed
        swKouter.stop();
        String time =swKouter.getElapsedTime();
        kouterTime.setText(time);
    }//GEN-LAST:event_kouterStopActionPerformed

    private void brosStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brosStopActionPerformed
        swBros.stop();
        String time =swBros.getElapsedTime();
        brosTime.setText(time);
    }//GEN-LAST:event_brosStopActionPerformed

    private void westlandiaStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westlandiaStopActionPerformed
        swWestlandia.stop();
        String time =swWestlandia.getElapsedTime();
        westlandiaTime.setText(time);
    }//GEN-LAST:event_westlandiaStopActionPerformed

    private void zkStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zkStopActionPerformed
        swZk.stop();
        String time =swZk.getElapsedTime();
        zkTime.setText(time);
    }//GEN-LAST:event_zkStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Core.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Core.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Core.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Core.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Core().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brechtStop;
    private javax.swing.JLabel brechtTime;
    private javax.swing.JButton brihosStop;
    private javax.swing.JLabel brihosTime;
    private javax.swing.JButton brosStop;
    private javax.swing.JLabel brosTime;
    private javax.swing.JButton ezelStop;
    private javax.swing.JLabel ezelTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton kouterStop;
    private javax.swing.JLabel kouterTime;
    private javax.swing.JLabel lMin;
    private javax.swing.JLabel lSec;
    private javax.swing.JLabel lUren;
    private javax.swing.JButton lilaStop;
    private javax.swing.JLabel lilaTime;
    private javax.swing.JButton reset;
    private javax.swing.JButton sdaStop;
    private javax.swing.JLabel sdaTime;
    private javax.swing.JButton start;
    private javax.swing.JButton westlandiaStop;
    private javax.swing.JLabel westlandiaTime;
    private javax.swing.JButton zkStop;
    private javax.swing.JLabel zkTime;
    // End of variables declaration//GEN-END:variables
    private StopWatch swBrecht,swBros,swEzel,swKouter,swLila,swSda,swWestlandia,swZk,swBrihos;
    private Timer msecT, secT, minT, hoursT;    
    private int msec=0, sec=0, min=0, hours=0;    
    }
